version: '3.1'

services:
  mysqlsrv:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dbase
    ports:
      - "3306:3306"
    networks:
    - mysql-compose-network

  adminer:
    image: adminer
    restart: always
    ports:
    - 8081:8080
    networks:
    - mysql-compose-network

networks: 
    mysql-compose-network:
      driver: bridge